# -*- coding: utf-8 -*-
"""ONNX.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVQmvd981QMQmhzf68fSjwW6JU4g2PT6
"""

!pip install tf2onnx

import tensorflow as tf
import tf2onnx
import numpy as np # Import numpy for dummy input

# Memuat model yang sudah disimpan dalam format .h5
model = tf.keras.models.load_model('/content/drive/MyDrive/saved_model/DLmobilenet_tomato_disease.h5')

# Mengonversi model ke format .onnx
onnx_model_path = '/content/drive/MyDrive/saved_model/DLmobilenet_tomato_disease.onnx'

# Get the concrete function from the Keras model
# We need to provide a dummy input to trace the function
dummy_input = tf.TensorSpec((None, 224, 224, 3), tf.float32, name="input") # Define input spec

# Get the concrete function by tracing the model call with the dummy input
@tf.function
def to_save(model_input):
    return model(model_input, training=False)

concrete_func = to_save.get_concrete_function(dummy_input)

# Mengonversi model menggunakan tf2onnx using the concrete function
# Specify input and output names for clarity in the ONNX graph
model_proto, external_tensor_storage = tf2onnx.convert.from_keras(
    model,
    input_signature=[dummy_input],
    opset=13 # Specify a compatible opset version, e.g., 13
)

# Menyimpan model ONNX
with open(onnx_model_path, "wb") as f:
    f.write(model_proto.SerializeToString())

print(f'Model berhasil dikonversi ke {onnx_model_path}')

import tensorflow as tf
import tf2onnx
import numpy as np # Import numpy for dummy input

# Memuat model yang sudah disimpan dalam format .h5
model = tf.keras.models.load_model('/content/drive/MyDrive/saved_model/mobilenetpengujian211_tomato_disease.h5')

# Mengonversi model ke format .onnx
onnx_model_path = '/content/drive/MyDrive/saved_model/mobilenetpengujian211_tomato_disease.onnx'

# Get the concrete function from the Keras model
# We need to provide a dummy input to trace the function
dummy_input = tf.TensorSpec((None, 224, 224, 3), tf.float32, name="input") # Define input spec

# Get the concrete function by tracing the model call with the dummy input
@tf.function
def to_save(model_input):
    return model(model_input, training=False)

concrete_func = to_save.get_concrete_function(dummy_input)

# Mengonversi model menggunakan tf2onnx using the concrete function
# Specify input and output names for clarity in the ONNX graph
model_proto, external_tensor_storage = tf2onnx.convert.from_keras(
    model,
    input_signature=[dummy_input],
    opset=13 # Specify a compatible opset version, e.g., 13
)

# Menyimpan model ONNX
with open(onnx_model_path, "wb") as f:
    f.write(model_proto.SerializeToString())

print(f'Model berhasil dikonversi ke {onnx_model_path}')

import tensorflow as tf
import tf2onnx
import numpy as np # Import numpy for dummy input

# Memuat model yang sudah disimpan dalam format .h5
model = tf.keras.models.load_model('/content/drive/MyDrive/saved_model/mobilenetpengujian2_tomato_disease.h5')

# Mengonversi model ke format .onnx
onnx_model_path = '/content/drive/MyDrive/saved_model/mobilenetpengujian2_tomato_disease.onnx'

# Get the concrete function from the Keras model
# We need to provide a dummy input to trace the function
dummy_input = tf.TensorSpec((None, 224, 224, 3), tf.float32, name="input") # Define input spec

# Get the concrete function by tracing the model call with the dummy input
@tf.function
def to_save(model_input):
    return model(model_input, training=False)

concrete_func = to_save.get_concrete_function(dummy_input)

# Mengonversi model menggunakan tf2onnx using the concrete function
# Specify input and output names for clarity in the ONNX graph
model_proto, external_tensor_storage = tf2onnx.convert.from_keras(
    model,
    input_signature=[dummy_input],
    opset=13 # Specify a compatible opset version, e.g., 13
)

# Menyimpan model ONNX
with open(onnx_model_path, "wb") as f:
    f.write(model_proto.SerializeToString())

print(f'Model berhasil dikonversi ke {onnx_model_path}')